// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice =
  | HeroBannerSlice
  | TextBlockSlice
  | ImageTextSlice
  | ResourceListSlice
  | CardsSlice
  | EmailSignupFormSlice
  | CallToActionSlice
  | DividerSlice
  | TestimonialSlice;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Page heading field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Page intro field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.page_intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_intro: prismic.RichTextField;

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

/**
 * Content for Background Colour documents
 */
interface BackgroundColourDocumentData {
  /**
   * Colour hexcode field in *Background Colour*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Only used if background should NOT be WHITE
   * - **API ID Path**: background_colour.colour_hexcode
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  colour_hexcode: prismic.KeyTextField;
}

/**
 * Background Colour document from Prismic
 *
 * - **API ID**: `background_colour`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BackgroundColourDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BackgroundColourDocumentData>,
    "background_colour",
    Lang
  >;

type BlogDocumentDataSlicesSlice = never;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Page title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Page intro field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.page_intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_intro: prismic.RichTextField;

  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BlogDocumentData>, "blog", Lang>;

type HomepageDocumentDataSlicesSlice =
  | ProductsSlice
  | CallToActionSlice
  | TestimonialSlice
  | EmailSignupFormSlice
  | DividerSlice
  | CardsSlice
  | HeroBannerSlice
  | TextBlockSlice
  | ImageTextSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | CallToActionSlice
  | ProductsSlice
  | TestimonialSlice
  | TestimonialListSlice
  | ResourceListSlice
  | EmailSignupFormSlice
  | DividerSlice
  | CardsSlice
  | HeroBannerSlice
  | ImageTextSlice
  | TextBlockSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Page heading field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Page intro field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.page_intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_intro: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProductDocumentDataSlicesSlice = never;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Product Name field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.product_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_name: prismic.KeyTextField;

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Price field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * Shipping text field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.shipping_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shipping_text: prismic.KeyTextField;

  /**
   * Payment link field in *Product*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Stripe payment link
   * - **API ID Path**: product.payment_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  payment_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Most Popular field in *Product*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: product.most_popular
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  most_popular: prismic.BooleanField;

  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
   * Meta Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

type ResourceDocumentDataSlicesSlice = never;

/**
 * Content for Resource documents
 */
interface ResourceDocumentData {
  /**
   * File field in *Resource*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.file
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  file: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Title field in *Resource*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Resource*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Button Label field in *Resource*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.button_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Slice Zone field in *Resource*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ResourceDocumentDataSlicesSlice> /**
   * Meta Title field in *Resource*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: resource.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Resource*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: resource.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Resource*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Resource document from Prismic
 *
 * - **API ID**: `resource`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResourceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ResourceDocumentData>,
    "resource",
    Lang
  >;

type TestimonialDocumentDataSlicesSlice = never;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Title field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Testimonial field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.testimonial
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testimonial: prismic.RichTextField;

  /**
   * Author field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Source field in *Testimonial*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.source
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  source: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Slice Zone field in *Testimonial*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TestimonialDocumentDataSlicesSlice> /**
   * Meta Title field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: testimonial.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: testimonial.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialDocumentData>,
    "testimonial",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleDocument
  | BackgroundColourDocument
  | BlogDocument
  | HomepageDocument
  | PageDocument
  | ProductDocument
  | ResourceDocument
  | TestimonialDocument;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Button field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Subtext field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtext: prismic.KeyTextField;

  /**
   * Background Colour field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"background_colour">;

  /**
   * Margin field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Top & Bottom
   * - **API ID Path**: call_to_action.default.primary.slice_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  slice_padding: prismic.SelectField<
    "Top & Bottom" | "Top Only" | "Bottom Only" | "No Margin",
    "filled"
  >;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Item in *Cards → Default → Primary → Card*
 */
export interface CardsSliceDefaultPrimaryCardItem {
  /**
   * Image field in *Cards → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.card[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Cards → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.card[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Copy field in *Cards → Default → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.card[].copy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;
}

/**
 * Primary content in *Cards → Default → Primary*
 */
export interface CardsSliceDefaultPrimary {
  /**
   * Heading field in *Cards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Cards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Card field in *Cards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<CardsSliceDefaultPrimaryCardItem>>;

  /**
   * Grid Columns Desktop field in *Cards → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.grid_columns_desktop
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  grid_columns_desktop: prismic.SelectField<"2" | "3" | "4">;

  /**
   * Grid Columns Tablet field in *Cards → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.grid_columns_tablet
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  grid_columns_tablet: prismic.SelectField<"2" | "3">;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cards*
 */
type CardsSliceVariation = CardsSliceDefault;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Cards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSlice = prismic.SharedSlice<"cards", CardsSliceVariation>;

/**
 * Default variation for Divider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DividerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Divider*
 */
type DividerSliceVariation = DividerSliceDefault;

/**
 * Divider Shared Slice
 *
 * - **API ID**: `divider`
 * - **Description**: Divider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DividerSlice = prismic.SharedSlice<
  "divider",
  DividerSliceVariation
>;

/**
 * Primary content in *EmailSignupForm → Default → Primary*
 */
export interface EmailSignupFormSliceDefaultPrimary {
  /**
   * Heading field in *EmailSignupForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: email_signup_form.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *EmailSignupForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: email_signup_form.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Klaviyo Form ID field in *EmailSignupForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: email_signup_form.default.primary.klaviyo_form_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  klaviyo_form_id: prismic.KeyTextField;

  /**
   * Background Colour field in *EmailSignupForm → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: email_signup_form.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"background_colour">;
}

/**
 * Default variation for EmailSignupForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmailSignupFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EmailSignupFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EmailSignupForm*
 */
type EmailSignupFormSliceVariation = EmailSignupFormSliceDefault;

/**
 * EmailSignupForm Shared Slice
 *
 * - **API ID**: `email_signup_form`
 * - **Description**: EmailSignupForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmailSignupFormSlice = prismic.SharedSlice<
  "email_signup_form",
  EmailSignupFormSliceVariation
>;

/**
 * Primary content in *HeroBanner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Heading field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Call To Action field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.call_to_action
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Background Image field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Overlay Colour field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.overlay_colour
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  overlay_colour: prismic.ColorField;

  /**
   * Overlay Opacity field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: A percentage of how transparent the colour overlay appears
   * - **API ID Path**: hero_banner.default.primary.overlay_opacity
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  overlay_opacity: prismic.NumberField;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Primary content in *ImageText → Image on LEFT → Primary*
 */
export interface ImageTextSliceDefaultPrimary {
  /**
   * Image field in *ImageText → Image on LEFT → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Round Image field in *ImageText → Image on LEFT → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_text.default.primary.round_image
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  round_image: prismic.BooleanField;

  /**
   * Copy field in *ImageText → Image on LEFT → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.copy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;

  /**
   * Background Colour field in *ImageText → Image on LEFT → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"background_colour">;
}

/**
 * Image on LEFT variation for ImageText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageText → Image on RIGHT → Primary*
 */
export interface ImageTextSliceImageOnRightPrimary {
  /**
   * Copy field in *ImageText → Image on RIGHT → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.imageOnRight.primary.copy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;

  /**
   * Image field in *ImageText → Image on RIGHT → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.imageOnRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Round Image field in *ImageText → Image on RIGHT → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_text.imageOnRight.primary.round_image
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  round_image: prismic.BooleanField;

  /**
   * Background Colour field in *ImageText → Image on RIGHT → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.imageOnRight.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"background_colour">;
}

/**
 * Image on RIGHT variation for ImageText Slice
 *
 * - **API ID**: `imageOnRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSliceImageOnRight = prismic.SharedSliceVariation<
  "imageOnRight",
  Simplify<ImageTextSliceImageOnRightPrimary>,
  never
>;

/**
 * Slice variation for *ImageText*
 */
type ImageTextSliceVariation =
  | ImageTextSliceDefault
  | ImageTextSliceImageOnRight;

/**
 * ImageText Shared Slice
 *
 * - **API ID**: `image_text`
 * - **Description**: ImageText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSlice = prismic.SharedSlice<
  "image_text",
  ImageTextSliceVariation
>;

/**
 * Item in *Products → Default → Primary → Products*
 */
export interface ProductsSliceDefaultPrimaryProductsItem {
  /**
   * Product field in *Products → Default → Primary → Products*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.products[].product
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product: prismic.ContentRelationshipField<"product">;
}

/**
 * Primary content in *Products → Default → Primary*
 */
export interface ProductsSliceDefaultPrimary {
  /**
   * Heading field in *Products → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Products → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Products field in *Products → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.products[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  products: prismic.GroupField<
    Simplify<ProductsSliceDefaultPrimaryProductsItem>
  >;

  /**
   * Grid Columns Desktop field in *Products → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.grid_columns_desktop
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  grid_columns_desktop: prismic.SelectField<"2" | "3" | "4">;

  /**
   * Grid Columns Tablet field in *Products → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.grid_columns_tablet
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  grid_columns_tablet: prismic.SelectField<"2" | "3">;
}

/**
 * Default variation for Products Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Products*
 */
type ProductsSliceVariation = ProductsSliceDefault;

/**
 * Products Shared Slice
 *
 * - **API ID**: `products`
 * - **Description**: Products
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSlice = prismic.SharedSlice<
  "products",
  ProductsSliceVariation
>;

/**
 * Item in *ResourceList → Default → Primary → Resources List*
 */
export interface ResourceListSliceDefaultPrimaryResourcesListItem {
  /**
   * Resource field in *ResourceList → Default → Primary → Resources List*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_list.default.primary.resources_list[].resource
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  resource: prismic.ContentRelationshipField<"resource">;
}

/**
 * Primary content in *ResourceList → Default → Primary*
 */
export interface ResourceListSliceDefaultPrimary {
  /**
   * Heading field in *ResourceList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_list.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *ResourceList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_list.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Resources List field in *ResourceList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_list.default.primary.resources_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  resources_list: prismic.GroupField<
    Simplify<ResourceListSliceDefaultPrimaryResourcesListItem>
  >;

  /**
   * Grid Columns Desktop field in *ResourceList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_list.default.primary.grid_columns_desktop
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  grid_columns_desktop: prismic.SelectField<"2" | "3" | "4">;

  /**
   * Grid Columns Tablet field in *ResourceList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_list.default.primary.grid_columns_tablet
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  grid_columns_tablet: prismic.SelectField<"2" | "3">;
}

/**
 * Default variation for ResourceList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResourceListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ResourceListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ResourceList*
 */
type ResourceListSliceVariation = ResourceListSliceDefault;

/**
 * ResourceList Shared Slice
 *
 * - **API ID**: `resource_list`
 * - **Description**: ResourceList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResourceListSlice = prismic.SharedSlice<
  "resource_list",
  ResourceListSliceVariation
>;

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Title field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Testimonial field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonial
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  testimonial: prismic.ContentRelationshipField<"testimonial">;

  /**
   * Background Colour field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"background_colour">;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Testimonial
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

/**
 * Item in *TestimonialList → Default → Primary → Testimonials*
 */
export interface TestimonialListSliceDefaultPrimaryTestimonialsItem {
  /**
   * Testimonial field in *TestimonialList → Default → Primary → Testimonials*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_list.default.primary.testimonials[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  testimonial: prismic.ContentRelationshipField<"testimonial">;
}

/**
 * Primary content in *TestimonialList → Default → Primary*
 */
export interface TestimonialListSliceDefaultPrimary {
  /**
   * heading field in *TestimonialList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_list.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *TestimonialList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_list.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Testimonials field in *TestimonialList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_list.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialListSliceDefaultPrimaryTestimonialsItem>
  >;

  /**
   * Grid Columns Desktop field in *TestimonialList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_list.default.primary.grid_columns_desktop
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  grid_columns_desktop: prismic.SelectField<"2" | "3" | "4">;

  /**
   * Grid Columns Tablet field in *TestimonialList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_list.default.primary.grid_columns_tablet
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  grid_columns_tablet: prismic.SelectField<"1" | "2" | "3">;
}

/**
 * Default variation for TestimonialList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialList*
 */
type TestimonialListSliceVariation = TestimonialListSliceDefault;

/**
 * TestimonialList Shared Slice
 *
 * - **API ID**: `testimonial_list`
 * - **Description**: TestimonialList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialListSlice = prismic.SharedSlice<
  "testimonial_list",
  TestimonialListSliceVariation
>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Text field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Background Colour field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"background_colour">;

  /**
   * Margin field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Top & Bottom
   * - **API ID Path**: text_block.default.primary.slice_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  slice_padding: prismic.SelectField<
    "Top & Bottom" | "Top Only" | "Bottom Only" | "No Margin",
    "filled"
  >;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      BackgroundColourDocument,
      BackgroundColourDocumentData,
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataSlicesSlice,
      ResourceDocument,
      ResourceDocumentData,
      ResourceDocumentDataSlicesSlice,
      TestimonialDocument,
      TestimonialDocumentData,
      TestimonialDocumentDataSlicesSlice,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CardsSlice,
      CardsSliceDefaultPrimaryCardItem,
      CardsSliceDefaultPrimary,
      CardsSliceVariation,
      CardsSliceDefault,
      DividerSlice,
      DividerSliceVariation,
      DividerSliceDefault,
      EmailSignupFormSlice,
      EmailSignupFormSliceDefaultPrimary,
      EmailSignupFormSliceVariation,
      EmailSignupFormSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      ImageTextSlice,
      ImageTextSliceDefaultPrimary,
      ImageTextSliceImageOnRightPrimary,
      ImageTextSliceVariation,
      ImageTextSliceDefault,
      ImageTextSliceImageOnRight,
      ProductsSlice,
      ProductsSliceDefaultPrimaryProductsItem,
      ProductsSliceDefaultPrimary,
      ProductsSliceVariation,
      ProductsSliceDefault,
      ResourceListSlice,
      ResourceListSliceDefaultPrimaryResourcesListItem,
      ResourceListSliceDefaultPrimary,
      ResourceListSliceVariation,
      ResourceListSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
      TestimonialListSlice,
      TestimonialListSliceDefaultPrimaryTestimonialsItem,
      TestimonialListSliceDefaultPrimary,
      TestimonialListSliceVariation,
      TestimonialListSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
